on: workflow_dispatch
name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # - name: Install Dependencies
      #   run: pip install -r requirements.txt
      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './.'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_AD_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: 'Fetching Azure Functions Publishing Profile'
        id: fncapp
        uses: azure/powershell@v1
        with:
          inlineScript: |
              $profile = ""
              $profile = Get-AzWebAppPublishingProfile -ResourceGroupName RG-WE-D-FUNCTIONS -Name azure-sentiment-analysis
              $profile = $profile.Replace("`r", "").Replace("`n", "")
              Write-Output "::set-output name=pubprofile::$profile"
              Remove-Variable profile
          azPSVersion: "latest"

      - name: 'Run Azure Functions Action'
        uses: azure/functions-action@v1
        with:
          app-name: azure-sentiment-analysis
          package: .
          publish-profile: ${{ steps.fncapp.outputs.pubprofile }}
      
      